NAME = diary-app

help:
	@echo "Available commands:"
	@echo ""
	@echo "  EVERY DAY:"
	@echo "    make build         - Compile native code, install APK, start Metro"
	@echo "    make dev           - Start Metro bundler only (no recompile)"
	@echo ""
	@echo "  CLEANUP (from least to most destructive):"
	@echo "    make clean         - Remove node_modules"
	@echo "    make clean-build   - Remove Android build output (~700MB)"
	@echo "    make clean-android - Remove entire android/ folder"
	@echo "    make clean-cache   - Remove Metro/Expo cache"
	@echo "    make clean-emulator- Wipe emulator data"
	@echo "    make fclean        - All of the above + lock file"
	@echo ""
	@echo "  NUCLEAR RESET:"
	@echo "    make re            - fclean + reinstall + prebuild + build"
	@echo ""
	@echo "  OTHER:"
	@echo "    make studio        - Boot Android emulator manually (no snapshot)"
	@echo "    make tunnel        - Start Metro with tunnel (for physical devices)"
	@echo "    make web           - Start Expo web"
	@echo "    make install       - Install JS dependencies"
	@echo "    make lint          - Run ESLint"
	@echo "    make depcheck      - Check for unused dependencies"

# ─── EMULATOR ────────────────────────────────────────────────────────────────

# Manual emulator boot — not needed in normal usage, make build handles it
studio:
	/goinfre/htharrau/android-sdk/emulator/emulator -avd Pixel_6 -no-snapshot-load &

# ─── DEVELOPMENT ─────────────────────────────────────────────────────────────

# Compiles native Android code, installs APK, starts Metro
# Slow (~2-5 min). Run once, or after adding a native module
build:
	npx expo run:android

pics: 
	adb push ~/goinfre/diary/diary-app/assets/images/* /sdcard/Pictures/  
	adb shell am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file:///sdcard/Pictures/

# Starts Metro bundler only — no recompile
# Use this daily once APK is already installed
dev:
	npx expo start --dev-client --clear

tunnel:
	npx expo start --dev-client --tunnel --clear

web:
	npx expo start --web

# ─── DEPENDENCIES ────────────────────────────────────────────────────────────

install:
	npm install --legacy-peer-deps

lint:
	npm run lint

depcheck:
	npx depcheck

# ─── CLEANUP ─────────────────────────────────────────────────────────────────

# Remove node_modules
clean:
	rm -rf node_modules
	rm -f package-lock.json

# Remove Android build output (~700MB)
clean-build:
	rm -rf android/app/build android/build

# Remove entire android/ folder (regenerated by prebuild)
clean-android:
	rm -rf android

# Remove Metro/Expo cache
clean-cache:
	rm -rf /tmp/metro-* ~/.expo/cache

# Wipe emulator data (boots fresh)
clean-emulator:
	rm -rf ~/.android/avd/Pixel_6.avd/*.img
	rm -rf ~/.android/avd/Pixel_6.avd/cache

# Remove everything
fclean: clean clean-build clean-android clean-cache clean-emulator

# ─── NUCLEAR RESET ───────────────────────────────────────────────────────────

# Full reset: wipe everything, reinstall, regenerate android/, rebuild
re: fclean
	-pkill -f "expo" 2>/dev/null; true
	-pkill -f "metro" 2>/dev/null; true
	$(MAKE) install
	npx expo prebuild --clean --platform android
	$(MAKE) build

.PHONY: help install build dev tunnel web studio clean clean-build clean-android clean-cache clean-emulator fclean re lint depcheck